DECLARE @CONTADOR INT, @COMPARADOR INT
DECLARE @CUSTOMERID NVARCHAR(50), @COMPANYNAME NVARCHAR(50)
DECLARE CLIENTEPAIS CURSOR
FOR


   SELECT CUSTOMERID, COMPANYNAME  FROM CUSTOMERS
     WHERE COUNTRY='Mexico'
   
      OPEN CLIENTEPAIS
       FETCH NEXT FROM CLIENTEPAIS
         INTO @CUSTOMERID, @COMPANYNAME

          WHILE @@FETCH_STATUS=0
	      BEGIN
		   SET @COMPARADOR =( select count(COUNTRY) from customers where country='mexico')
		    SET @CONTADOR=(SELECT COUNT(CUSTOMERID) FROM CUSTOMERS WHERE
			  COUNTRY='Mexico')
			   UPDATE CUSTOMERS SET COUNTRY='Mex' WHERE @CUSTOMERID=CUSTOMERID AND @COMPANYNAME=COMPANYNAME
			     AND @CONTADOR=@COMPARADOR
		   

	        FETCH NEXT FROM CLIENTEPAIS
	         INTO @CUSTOMERID, @COMPANYNAME

	      END

CLOSE CLIENTEPAIS
DEALLOCATE CLIENTEPAIS

