CREATE FUNCTION AGRUPALF(@BASERATE MONEY)
RETURNS NVARCHAR(50)
AS

 BEGIN
 DECLARE @LASTNAME NVARCHAR (50)
 DECLARE @FIRSTNAME NVARCHAR(50)
 DECLARE @NAME NVARCHAR(50)
 SELECT @BASERATE=BASERATE, @FIRSTNAME=FIRSTNAME,
         @LASTNAME=LASTNAME, @NAME=CONCAT(@FIRSTNAME,',',@LASTNAME) FROM DimEmployee
		   WHERE BASERATE=@BASERATE AND BASERATE <>0
RETURN @NAME
END
GO

SELECT DBO.AGRUPALF(BASERATE) FROM DimEmployee