CREATE FUNCTION COMPARACADENAS(@PALABRA1 NVARCHAR(10))
RETURNS NVARCHAR(10)
AS
BEGIN

DECLARE @PALABRA2 NVARCHAR(10)
  SET @PALABRA2='CANTILLO'
    DECLARE @PALABRA NVARCHAR (10)
      SELECT @PALABRA=@PALABRA2 WHERE @PALABRA1=@PALABRA2

RETURN @PALABRA
END


SELECT DBO.COMPARACADENAS ('CANTILLO')

DROP FUNCTION COMPARACADENAS