
CREATE FUNCTION REDONDEO(@PRECIO money)
RETURNS money
AS
BEGIN
SELECT @PRECIO=(ISNULL(ROUND(STANDARDCOST,1),0))   FROM DimProduct
   WHERE  (ISNULL(ROUND(STANDARDCOST,1),0))<> 0  AND STANDARDCOST=@PRECIO
RETURN @PRECIO
END
GO


SELECT * , DBO.REDONDEO(STANDARDCOST) FROM DIMPRODUCT