SELECT TOP 5 LISTPRICE FROM DIMPRODUCT
ORDER BY LISTPRICE DESC


SELECT TOP 5 LISTPRICE FROM DIMPRODUCT
WHERE LISTPRICE <=600
ORDER BY LISTPRICE DESC

SELECT  LISTPRICE FROM DIMPRODUCT
ORDER BY LISTPRICE DESC
OFFSET 5 ROW

SELECT LISTPRICE, * FROM DIMPRODUCT