SELECT DISTINCT
      SQ.NOMBRES,
	    SQ.BaseRate,
		  SQ.[2019],
		    SQ.[2020],
			  SUM(BASERATE) + SUM(SQ.[2019]) + SUM (SQ.[2020]) AS TOTAL
FROM
(SELECT DBO.AGRUPALF (BASERATE) AS 'NOMBRES',
              BASERATE,
	             (BASERATE / 100 * 8) AS '2019',
	                (BASERATE /100 *16) AS '2020'
FROM DIMEMPLOYEE
GROUP BY BASERATE) AS SQ
GROUP BY SQ.BaseRate, SQ.[2019], SQ.[2020], SQ.NOMBRES






