CREATE TRIGGER UPDATEDIMEMPLOYEE ON DIMEMPLOYEE
AFTER UPDATE
AS

BEGIN 
  IF update (title)
     IF(SELECT TITLE FROM inserted)='otro'
	 BEGIN
	  RAISERROR('NO SE PUEDE MODIFICAR EL CARGO,
	             CONSULTE AL ADMINISTRADOR DEL SISTEMA',15,1)
	       ROLLBACK
		   END
END

GO

SELECT title FROM DimEmployee where EmployeeKey=1

UPDATE DimEmployee SET TITLE='otro' where EmployeeKey=1

DISABLE TRIGGER  UPDATEDEMPLOYEE ON DIMEMPLOYEE