CREATE TRIGGER NOUPDATE ON DIMPRODUCT
FOR UPDATE
AS

SET NOCOUNT ON
DECLARE @STOCKLEVEL SMALLINT
SET @STOCKLEVEL =1000

BEGIN
        IF UPDATE(SAFETYSTOCKLEVEL)
		  IF EXISTS( SELECT P.SAFETYSTOCKLEVEL FROM DIMPRODUCT P
		               INNER JOIN INSERTED R ON
					      P.SAFETYSTOCKLEVEL = R.SAFETYSTOCKLEVEL
						    WHERE R.SAFETYSTOCKLEVEL <=@STOCKLEVEL)
		       BEGIN
			    PRINT 'DATOS ACTUALIZADOS'
			     END

			 ELSE
			     BEGIN
			       RAISERROR ('LA OPERACION SOLO PERMITE ACTUALIZAR VALORES DE STOCK INFERIORES A 1000',15,1)
			        ROLLBACK
			      END
END
GO





SELECT (SafetyStockLevel), ProductKey FROM DIMPRODUCT WHERE ProductKey IN (1,2)

UPDATE DimProduct SET SafetyStockLevel=1002 WHERE ProductKey IN (1,2)


DISABLE TRIGGER NOUPDATE ON DIMEMPLOYEE

DROP TRIGGER NOUPDATE





