DECLARE @QUERY NVARCHAR(50)
DECLARE @CONTADOR INT;
DECLARE @CONTADOR2 INT;
SET @CONTADOR=0;
SET @CONTADOR2=(SELECT COUNT(CONTACTNAME) FROM Suppliers)

WHILE (@CONTADOR<=@CONTADOR2)

BEGIN
         SET @QUERY=(SELECT CONTACTNAME FROM SUPPLIERS WHERE COUNTRY='USA'
             AND SupplierID= @CONTADOR)
			  SET @CONTADOR= @CONTADOR +1
              PRINT  @QUERY
			  
END

